"use client";

import {useEffect,useState} from "react";

export default function IdentityReview(){
 const [items,setItems]=useState<any[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState("");
 async function load(){const r=await fetch("/api/identity/admin");const d=await r.json();if(r.ok)setItems(d.verifications||[]);else setError(d.error||"Forbidden");}
 useEffect(()=>{load()},[]);
 async function openDocument(id:string,kind:"document"|"selfie"){const r=await fetch("/api/identity/document?verificationId="+encodeURIComponent(id)+"&kind="+kind);const d=await r.json();if(!r.ok){setError(d.error||"تعذر فتح الملف");return;}window.open(d.url,"_blank","noopener,noreferrer");}
 async function review(id:string,status:"VERIFIED"|"REJECTED"){setBusy(id+status);const r=await fetch("/api/identity/review",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({verificationId:id,status,rejectionReason:"Identity documents could not be verified."})});const d=await r.json();if(!r.ok)setError(d.error||"Review failed");await load();setBusy("");}
 return <main dir="rtl" className="min-h-screen bg-[#f7f8fa] p-5 text-[#101828]"><div className="mx-auto max-w-6xl"><a href="/ops" className="text-sm text-[#667085]">← العمليات</a><div className="mt-5"><p className="text-xs font-semibold tracking-[.16em] text-[#c89252]">JELAD TRUST</p><h1 className="mt-1 text-3xl font-semibold">مراجعة الهويات</h1></div>{error&&<p className="mt-4 rounded-2xl bg-white p-4 text-sm text-[#b42318]">{error}</p>}<div className="mt-6 space-y-3">{items.map(v=><article key={v.id} className="rounded-3xl bg-white p-5 ring-1 ring-[#eaecf0]"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-semibold">{v.profiles?.full_name||"User"}</p><p className="mt-1 text-sm text-[#667085]">{v.subject_type==="DRIVER"?"سائقة":"عميلة"} · {v.gender==="female"?"أنثى":"ذكر"} · {v.document_type||"Document"}</p></div><span className="rounded-full bg-[#eef2f6] px-3 py-1 text-xs font-semibold">{v.status}</span></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>openDocument(v.id,"document")} className="rounded-xl border border-[#eaecf0] px-4 py-2 text-xs font-semibold">عرض الهوية (5 دقائق)</button><button onClick={()=>openDocument(v.id,"selfie")} className="rounded-xl border border-[#eaecf0] px-4 py-2 text-xs font-semibold">عرض السيلفي (5 دقائق)</button></div>{v.status==="PENDING"&&<div className="mt-4 flex gap-2"><button disabled={!!busy} onClick={()=>review(v.id,"VERIFIED")} className="rounded-xl bg-[#182230] px-4 py-2 text-xs font-semibold text-white">قبول</button><button disabled={!!busy} onClick={()=>review(v.id,"REJECTED")} className="rounded-xl border border-[#eaecf0] px-4 py-2 text-xs font-semibold">رفض</button></div>}</article>)}</div></div></main>
}