"use client";
import { useState } from "react";

const services=[["Ride","Get where you need to go, simply."],["Delivery","Send packages across the city."],["Cargo","Move larger loads with confidence."],["Business","Manage company mobility in one place."]];
const quick=[["⌖","Set pickup"],["＋","Add destination"],["◷","Schedule"],["▣","Business"]];

export default function Home(){
 const [active,setActive]=useState("Ride");
 return <main className="min-h-screen bg-[#f7f8fa] text-[#101828]">
  <header className="sticky top-0 z-20 border-b border-[#eaecf0] bg-white/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#182230] text-sm font-bold text-white">J</div><span className="text-lg font-semibold tracking-[.18em]">JELAD</span></div><nav className="hidden gap-7 text-sm text-[#667085] md:flex"><a href="#services">Services</a><a href="#business">Business</a><a href="#safety">Safety</a></nav><button className="rounded-full bg-[#182230] px-4 py-2 text-sm font-medium text-white">Sign in</button></div></header>
  <section className="mx-auto grid max-w-6xl gap-8 px-5 pb-14 pt-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pt-16">
   <div><div className="mb-4 inline-flex rounded-full bg-white px-3 py-1.5 text-xs font-medium text-[#667085] shadow-sm ring-1 ring-[#eaecf0]">Mobility · Delivery · Business</div><h1 className="max-w-xl text-5xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-6xl">Move through your day with less friction.</h1><p className="mt-5 max-w-lg text-base leading-7 text-[#667085]">One simple platform for rides, deliveries and business mobility — designed around clarity, safety and time.</p><div className="mt-8 flex flex-wrap gap-3">{quick.map(([icon,label])=><button key={label} onClick={()=>setActive(label)} className="rounded-2xl bg-white px-4 py-3 text-sm font-medium shadow-sm ring-1 ring-[#eaecf0] transition hover:-translate-y-0.5">{icon} <span className="ml-1">{label}</span></button>)}</div></div>
   <div className="rounded-[28px] bg-[#182230] p-3 shadow-xl"><div className="rounded-[22px] bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs text-[#667085]">Where are you going?</p><h2 className="mt-1 text-xl font-semibold">{active==="Ride"?"Request a ride":"Plan your trip"}</h2></div><div className="rounded-xl bg-[#f2f4f7] px-3 py-2 text-xs font-medium">Zarqa · Jordan</div></div><div className="mt-5 space-y-3"><div className="flex items-center gap-3 rounded-2xl border border-[#eaecf0] p-4"><span className="h-2.5 w-2.5 rounded-full bg-[#182230]"></span><div><p className="text-xs text-[#98a2b3]">Pickup</p><p className="text-sm font-medium">Current location</p></div></div><div className="flex items-center gap-3 rounded-2xl border border-[#eaecf0] p-4"><span className="h-2.5 w-2.5 rounded-full bg-[#c89252]"></span><div><p className="text-xs text-[#98a2b3]">Destination</p><p className="text-sm font-medium">Search destination</p></div></div></div><button className="mt-4 w-full rounded-2xl bg-[#182230] py-4 text-sm font-semibold text-white">Continue</button></div></div>
  </section>
  <section id="services" className="border-y border-[#eaecf0] bg-white"><div className="mx-auto max-w-6xl px-5 py-14"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#c89252]">One platform</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.03em]">Everything you need to move.</h2></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map(([title,desc],i)=><article key={title} className="rounded-3xl border border-[#eaecf0] p-6 transition hover:-translate-y-1 hover:shadow-lg"><div className="mb-8 grid h-10 w-10 place-items-center rounded-xl bg-[#f2f4f7] text-sm font-bold">0{i+1}</div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#667085]">{desc}</p></article>)}</div></div></section>
  <section id="safety" className="mx-auto max-w-6xl px-5 py-14"><div className="rounded-[30px] bg-[#eef2f6] p-7 sm:p-10"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#667085]">Built differently</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.03em]">Clarity first. Safety always.</h2><p className="mt-4 leading-7 text-[#667085]">Transparent trip details, driver information, live status and safety tools are designed into the experience instead of being hidden behind menus.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-3">{["Live trip status","Verified drivers","Share & SOS"].map(x=><div key={x} className="rounded-2xl bg-white p-4 text-sm font-medium">{x}</div>)}</div></div></section>
  <footer className="border-t border-[#eaecf0] bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-5 py-7 text-sm text-[#667085] sm:flex-row sm:items-center sm:justify-between"><span>© 2026 JELAD</span><span>Mobility · Logistics · Technology</span></div></footer>
 </main>
}
